
import java.awt.print.PrinterException;
import javax.swing.table.DefaultTableModel;

import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import java.sql.*;
import java.util.ArrayList;
import java.util.Vector;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author dipanjanghosh
 */
public class JavaPOS extends javax.swing.JFrame {

    private int NULL;

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    Connection con;
    PreparedStatement pstm;
    ResultSet res;
//==========================================Function===================================

    public void itemCost(){
        double sum = 0;
        for ( int i = 0; i< jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 3.9)/100;
        
        String iTaxTotal = String.format("INR %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("INR %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("INR %.2f", cTotal1+cTax);
        jtxtTotal.setText(iTotal);
        
        String barCode = String.format("Total is %.2f", cTotal1+cTax);
        jtxtBarcode.setText(barCode);
        
        
    }
    //==========================================Function changer===================================
    
    public void change(){
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for ( int i = 0; i< jTable1.getRowCount(); i++){
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9)/100;
        double cChange = (cash - (sum+cTax));
        
        String changeGiven = String.format("INR %.2f", cChange);
        jtxtChange.setText(changeGiven);
    }
    
    public ArrayList getData(int id){
        ArrayList al = new ArrayList();
        String price = "";
        String item_name = "";
        try {
            
        Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Driver Loaded");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/javaPos","root","himalayan");
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Connection Established");
            // String sql = "Select * From Ecommerce";
            String sql = "Select * From products where id=?";
            
            
        try {
            pstm=con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pstm.setInt(1, id);
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            res=pstm.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while (res.next()==true) {
                
                
                price= res.getString(3);
//                System.out.println(price);
                item_name = res.getString(2);
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        al.add(item_name);
        al.add(price);
        return al;
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBtnVanillaMousse = new javax.swing.JButton();
        jBtnCupCake = new javax.swing.JButton();
        jBtnCreamCake = new javax.swing.JButton();
        jBtnChocoMousse = new javax.swing.JButton();
        jBtnChocoLavaCake = new javax.swing.JButton();
        jBtnSmallPizza = new javax.swing.JButton();
        jBtnOrangeJuice = new javax.swing.JButton();
        jBtnRainboCake = new javax.swing.JButton();
        jBtnRawCoffee = new javax.swing.JButton();
        jBtnOatsSmoothie = new javax.swing.JButton();
        jBtnEspresso = new javax.swing.JButton();
        jBtnMeduimPizza = new javax.swing.JButton();
        jBtnIceTea = new javax.swing.JButton();
        jBtnBlackCoffee = new javax.swing.JButton();
        jBtnChickenWings = new javax.swing.JButton();
        jBtnCreamRoll = new javax.swing.JButton();
        jBtnMuttonBurger = new javax.swing.JButton();
        jBtnLargePizza = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jBtn9 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnC = new javax.swing.JButton();
        jBtnPoint = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jComboPayment = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jbtnReset = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jtxtBarcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtnVanillaMousse.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jBtnVanillaMousse.setText("Vanilla Mousse");
        jBtnVanillaMousse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVanillaMousseActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnVanillaMousse, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 100));

        jBtnCupCake.setBackground(new java.awt.Color(242, 242, 242));
        jBtnCupCake.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnCupCake.setText("Cup Cake");
        jBtnCupCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCupCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCupCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 100));

        jBtnCreamCake.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnCreamCake.setText("Cream Cake");
        jBtnCreamCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreamCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCreamCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 100));

        jBtnChocoMousse.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jBtnChocoMousse.setText("Choco Mousse");
        jBtnChocoMousse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChocoMousseActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnChocoMousse, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 100));

        jBtnChocoLavaCake.setBackground(new java.awt.Color(0, 0, 0));
        jBtnChocoLavaCake.setFont(new java.awt.Font("Helvetica Neue", 1, 8)); // NOI18N
        jBtnChocoLavaCake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2023-02-17 at 10.16.23 AM.png"))); // NOI18N
        jBtnChocoLavaCake.setText("Choco Lava Cake");
        jBtnChocoLavaCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChocoLavaCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnChocoLavaCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 100));

        jBtnSmallPizza.setBackground(new java.awt.Color(51, 51, 51));
        jBtnSmallPizza.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnSmallPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/istockphoto-639963606-1024x1024.jpg"))); // NOI18N
        jBtnSmallPizza.setText("Small Pizza");
        jBtnSmallPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSmallPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSmallPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 100));

        jBtnOrangeJuice.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnOrangeJuice.setText("Orange Juice");
        jBtnOrangeJuice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOrangeJuiceActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOrangeJuice, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 110, 100));

        jBtnRainboCake.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnRainboCake.setText(" Rainbo Cake");
        jBtnRainboCake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRainboCakeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRainboCake, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, 100));

        jBtnRawCoffee.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnRawCoffee.setText("Raw Coffee");
        jBtnRawCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRawCoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnRawCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 110, 100));

        jBtnOatsSmoothie.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jBtnOatsSmoothie.setText("Oats smoothie");
        jBtnOatsSmoothie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOatsSmoothieActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnOatsSmoothie, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 110, 100));

        jBtnEspresso.setBackground(new java.awt.Color(0, 0, 0));
        jBtnEspresso.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnEspresso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2023-02-17 at 10.14.14 AM.png"))); // NOI18N
        jBtnEspresso.setText("Espresso");
        jBtnEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEspressoActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 110, 100));

        jBtnMeduimPizza.setBackground(new java.awt.Color(0, 0, 0));
        jBtnMeduimPizza.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnMeduimPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pizza-isolate-medium-size-top-view-stock-photo-of-pizza-2AE8F4H.jpg"))); // NOI18N
        jBtnMeduimPizza.setText("Medium Pizza");
        jBtnMeduimPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMeduimPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMeduimPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 110, 100));

        jBtnIceTea.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnIceTea.setText("Ice Tea");
        jBtnIceTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIceTeaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnIceTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 100));

        jBtnBlackCoffee.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnBlackCoffee.setText("Black Coffee");
        jBtnBlackCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBlackCoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnBlackCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 110, 100));

        jBtnChickenWings.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jBtnChickenWings.setText("Chicken Wings");
        jBtnChickenWings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnChickenWingsActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnChickenWings, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 110, 100));

        jBtnCreamRoll.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jBtnCreamRoll.setText("Cream Roll");
        jBtnCreamRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCreamRollActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnCreamRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, 100));

        jBtnMuttonBurger.setBackground(new java.awt.Color(0, 0, 0));
        jBtnMuttonBurger.setFont(new java.awt.Font("Helvetica Neue", 1, 10)); // NOI18N
        jBtnMuttonBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2023-02-17 at 10.10.42 AM.png"))); // NOI18N
        jBtnMuttonBurger.setText("Mutton Burger");
        jBtnMuttonBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnMuttonBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnMuttonBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 110, 100));

        jBtnLargePizza.setBackground(new java.awt.Color(0, 0, 0));
        jBtnLargePizza.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jBtnLargePizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/big-pizza-with-a-barbecue-on-a-wooden-table-PGCEYY.jpg"))); // NOI18N
        jBtnLargePizza.setText("Large Pizza");
        jBtnLargePizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLargePizzaActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLargePizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 110, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 730, 410));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBtn9.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 90, 80));

        jBtn7.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 80));

        jBtn8.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 90, 80));

        jBtn4.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 80));

        jBtn5.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, 80));

        jBtn6.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 90, 80));

        jBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 90, 80));

        jBtn2.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, 90, 80));

        jBtn3.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 90, 80));

        jBtnC.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtnC.setText("C");
        jBtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 90, 80));

        jBtnPoint.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtnPoint.setText(".");
        jBtnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPointActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnPoint, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 90, 80));

        jBtn0.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jBtn0.setText("0");
        jBtn0.setToolTipText("");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 90, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 410));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 320, 360));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel5.setText("Cash");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 40));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel6.setText("Change");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 40));

        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 160, 40));

        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel5.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, 40));

        jComboPayment.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jComboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Mater Card" }));
        jPanel5.add(jComboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 160, 40));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 460, 160));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setText("Total");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel2.setText("Sub Total");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 40));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel3.setText("Tax");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 40));
        jPanel6.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 240, 40));
        jPanel6.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 13, 240, 40));
        jPanel6.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 240, 40));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 160));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnReset.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 200, 40));

        jbtnRemove.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 200, 40));

        jbtnPay.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jbtnPay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnPayKeyPressed(evt);
            }
        });
        jPanel3.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        jbtnExit.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnExit.setText("EXIT");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 410, 40));

        jbtnPrint.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 200, 40));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 430, 160));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1380, 180));

        jtxtBarcode.setFont(new java.awt.Font("barcode font", 1, 48)); // NOI18N
        jtxtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarcodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 320, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn9.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn9.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn7.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn7.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn8.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn8.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn4.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn4.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn5.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn5.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn6.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn6.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn1.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn1.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
       String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn2.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn2.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn3.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn3.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jBtnCActionPerformed

    private void jBtnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPointActionPerformed
        if(! jtxtDisplay.getText().contains(".")){
            jtxtDisplay.setText(jtxtDisplay.getText() + jBtnPoint.getText());
        }
    }//GEN-LAST:event_jBtnPointActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
        String EnterNumber = jtxtDisplay.getText();
        if(EnterNumber == ""){
            jtxtDisplay.setText(jBtn0.getText());
        }else{
            EnterNumber = jtxtDisplay.getText() + jBtn0.getText();
            jtxtDisplay.setText(EnterNumber);
        }
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtnVanillaMousseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVanillaMousseActionPerformed
        ArrayList data = getData(2);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnVanillaMousseActionPerformed

    private void jBtnCupCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCupCakeActionPerformed
        ArrayList data = getData(1);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
          
    }//GEN-LAST:event_jBtnCupCakeActionPerformed

    private void jBtnCreamCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreamCakeActionPerformed
        ArrayList data = getData(3);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnCreamCakeActionPerformed

    private void jBtnChocoMousseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChocoMousseActionPerformed
        ArrayList data = getData(4);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnChocoMousseActionPerformed

    private void jBtnChocoLavaCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChocoLavaCakeActionPerformed
        ArrayList data = getData(5);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnChocoLavaCakeActionPerformed

    private void jBtnSmallPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSmallPizzaActionPerformed
        ArrayList data = getData(6);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnSmallPizzaActionPerformed

    private void jBtnOrangeJuiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOrangeJuiceActionPerformed
        ArrayList data = getData(7);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnOrangeJuiceActionPerformed

    private void jBtnRainboCakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRainboCakeActionPerformed
        ArrayList data = getData(8);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnRainboCakeActionPerformed

    private void jBtnRawCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRawCoffeeActionPerformed
        ArrayList data = getData(9);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnRawCoffeeActionPerformed

    private void jBtnOatsSmoothieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOatsSmoothieActionPerformed
        ArrayList data = getData(10);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnOatsSmoothieActionPerformed

    private void jBtnEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEspressoActionPerformed
        ArrayList data = getData(18);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnEspressoActionPerformed

    private void jBtnMeduimPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMeduimPizzaActionPerformed
        ArrayList data = getData(11);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnMeduimPizzaActionPerformed

    private void jBtnIceTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIceTeaActionPerformed
        ArrayList data = getData(12);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnIceTeaActionPerformed

    private void jBtnBlackCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBlackCoffeeActionPerformed
        ArrayList data = getData(13);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnBlackCoffeeActionPerformed

    private void jBtnChickenWingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnChickenWingsActionPerformed
        ArrayList data = getData(17);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnChickenWingsActionPerformed

    private void jBtnCreamRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCreamRollActionPerformed
        ArrayList data = getData(14);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnCreamRollActionPerformed

    private void jBtnMuttonBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnMuttonBurgerActionPerformed
        ArrayList data = getData(15);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnMuttonBurgerActionPerformed

    private void jBtnLargePizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLargePizzaActionPerformed
        ArrayList data = getData(16);
        String item_name = (String) data.get(0);
        String price = (String) data.get(1);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{item_name,"1",price});
        itemCost();
    }//GEN-LAST:event_jBtnLargePizzaActionPerformed

    private void jtxtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarcodeActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int removeItem = jTable1.getSelectedRow();
        
        if(removeItem >= 0){
            model.removeRow(removeItem);
        }
        itemCost();
        
        if(jComboPayment.getSelectedItem().equals("Cash")){
            change();
        }else{
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
    }//GEN-LAST:event_jbtnRemoveActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jComboPayment.getSelectedItem().equals("Cash")){
            change();
        }else{
            jtxtChange.setText("");
            jtxtDisplay.setText("");
        }
        
        String change = jtxtChange.getText();
        String display = jtxtDisplay.getText();
        String payment_type = (String) jComboPayment.getSelectedItem();
        
        String total = jtxtTotal.getText();
        
        try {
            
        Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Driver Loaded");
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/javaPos","root","himalayan");
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
            System.out.println("Connection Established");

            String sql = "Insert Into orders (id,total_price, payment_type, cash_given, balance_returned) Values(?,?,?,?,?)";
            
            
        try {
            pstm=con.prepareStatement(sql);
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            pstm.setInt(1,NULL);
            pstm.setString(2, total);            
            pstm.setString(3, payment_type);
            pstm.setString(4, display);
            pstm.setString(5, change);


        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            pstm.executeUpdate();
            // getting id from orders table
            Integer id = null;
            String sql2 = "SELECT MAX(id) as id FROM `orders`";
            pstm=con.prepareStatement(sql2);
            res=pstm.executeQuery();
            while (res.next()==true) {
			
                id = res.getInt(1);
                
            }
            Integer order_id = id;
            // add data on order_items table
            String item,quantity,amount;
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            for(int i =0; i< model.getRowCount(); i++){
                item=(String) model.getValueAt(i, 0);
                quantity = (String) model.getValueAt(i, 1);
                amount = (String) model.getValueAt(i, 2);
                
                String sql1 = "Insert Into orders_items (id,order_id, item, quantity, amount) Values(?,?,?,?,?)";
                pstm = con.prepareStatement(sql1);
                
                pstm.setInt(1,NULL);
                pstm.setInt(2, order_id);            
                pstm.setString(3, item);
                pstm.setString(4, quantity);
                pstm.setString(5, amount);
                
                pstm.executeUpdate();
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
   
        try {
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(JavaPOS.class.getName()).log(Level.SEVERE, null, ex);
        }


     
    }//GEN-LAST:event_jbtnPayActionPerformed
    private JFrame frame;
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit", "POS", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        
        MessageFormat header = new MessageFormat("Printing in progress");
        
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
            try {
                jTable1.print(JTable.PrintMode.NORMAL,header,footer);
            } catch (PrinterException ex) {
                System.err.format("No Printer Found", ex.getMessage());
            }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarcode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed
    
    
    private void jbtnPayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnPayKeyPressed
        
//        KeyEvent.VK_
        
        
        
        
        
        
        
    }//GEN-LAST:event_jbtnPayKeyPressed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnBlackCoffee;
    private javax.swing.JButton jBtnC;
    private javax.swing.JButton jBtnChickenWings;
    private javax.swing.JButton jBtnChocoLavaCake;
    private javax.swing.JButton jBtnChocoMousse;
    private javax.swing.JButton jBtnCreamCake;
    private javax.swing.JButton jBtnCreamRoll;
    private javax.swing.JButton jBtnCupCake;
    private javax.swing.JButton jBtnEspresso;
    private javax.swing.JButton jBtnIceTea;
    private javax.swing.JButton jBtnLargePizza;
    private javax.swing.JButton jBtnMeduimPizza;
    private javax.swing.JButton jBtnMuttonBurger;
    private javax.swing.JButton jBtnOatsSmoothie;
    private javax.swing.JButton jBtnOrangeJuice;
    private javax.swing.JButton jBtnPoint;
    private javax.swing.JButton jBtnRainboCake;
    private javax.swing.JButton jBtnRawCoffee;
    private javax.swing.JButton jBtnSmallPizza;
    private javax.swing.JButton jBtnVanillaMousse;
    private javax.swing.JComboBox<String> jComboPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JTextField jtxtBarcode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
